<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260924171847 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recurring_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, amount NUMERIC(20, 2) NOT NULL, type VARCHAR(20) NOT NULL, category VARCHAR(50) NOT NULL, frequency VARCHAR(20) NOT NULL, next_due_date DATE NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3509AA67E3C61F9 ON recurring_transaction (owner_id)');
        $this->addSql('ALTER TABLE recurring_transaction ADD CONSTRAINT FK_D3509AA67E3C61F9 FOREIGN KEY (owner_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recurring_transaction DROP CONSTRAINT FK_D3509AA67E3C61F9');
        $this->addSql('DROP TABLE recurring_transaction');
    }
}
